<?php
$this->headTitle('Page not found');
?>
<h1><?php echo trim($this->message, '.') ?></h1>

<?php if (isset($this->reason) && $this->reason): ?>

<?php
$reasonMessage= '';
switch ($this->reason) {
    case 'error-controller-cannot-dispatch':
        $reasonMessage = 'The requested controller was unable to dispatch the request.';
        break;
    case 'error-controller-not-found':
        $reasonMessage = 'The requested controller could not be mapped to an existing controller class.';
        break;
    case 'error-controller-invalid':
        $reasonMessage = 'The requested controller was not dispatchable.';
        break;
    case 'error-router-no-match':
        $reasonMessage = 'The requested URL could not be matched by routing.';
        break;
    default:
        $reasonMessage = 'We cannot determine at this time why a 404 was generated.';
        break;
}
?>

<p>Sorry, the page you were looking for cannot be found. <?php echo $reasonMessage ?></p>

<p>
    <a href="http://www.flickr.com/photos/hikingartist/8287082967/"><img src="http://farm9.staticflickr.com/8357/8287082967_58eef6b2cb_b.jpg" class="full-width"></a><br>
    <em>Image courtesy of Frits Ahlefeldt, <a href="http://hikingartist.com">hikingartist.com</a></em>
</p>

<p>If you got here by following a link from outside this website then that link may be out of date. Your best bet is to go back to the <a href="/">home page</a> and browse from there.</p>

<p>If the bad link was within the this website then I screwed up and I would appreciate it if you could <a href="/contact">let me know</a>.</p>

<?php endif ?>

<?php if (isset($this->controller) && $this->controller): ?>

<dl>
    <dt>Controller:</dt>
    <dd><?php echo $this->escapeHtml($this->controller) ?>
<?php
if (isset($this->controller_class)
    && $this->controller_class
    && $this->controller_class != $this->controller
) {
    echo " (resolves to " . $this->escapeHtml($this->controller_class) . ")";
}
?>
</dd>
</dl>

<?php endif ?>

<?php if (isset($this->exception) && $this->exception): ?>

<h2>Exception:</h2>

<p><b><?php echo $this->escapeHtml($this->exception->getMessage()) ?></b></p>

<h3>Stack trace</h3>

<pre>
<?php echo $this->exception->getTraceAsString() ?>
</pre>

<?php endif ?>