<?php
    $this->headTitle()->set('Contact')->append('Jurian Sluiman');
    $this->layout()->pagetype = 'ContactPage';
?>

<section class="blog-article about-me">
    <h1>Jurian Sluiman &middot; contact me</h1>

    <p>You can always contact me via <a href="mailto:jurian@juriansluiman.nl">jurian@juriansluiman.nl</a>. There are also various profiles on social networks you can use to get in touch.</p>

    <h2>Profiles</h2>
    <ul>
        <li><a href="https://twitter.com/juriansluiman">@juriansluiman</a> on Twitter</li>
        <li><a href="https://plus.google.com/102726331143136952916">+Jurian Sluiman</a> on Google+</li>
        <li><a href="https://linkedin.com/in/juriansluiman">Jurian Sluiman</a> on LinkedIn</li>
        <li><a href="https://github.com/juriansluiman">juriansluiman</a> on Github</li>
    </ul>
</section>