<article class="article" itemprop="blogPosts" itemscope itemtype="http://schema.org/BlogPosting">
    <header class="cf">
        <time datetime="2011-11-06T13:42:04+01:00" pubdate itemprop="datePublished" content="2011-11-06">november 2011</time>
        <h1 itemprop="name"><a href="" itemprop="url">Interface injection with initializers in Zend\ServiceManager</a></h1>
    </header>

    <ul>
        <li><h2><a href="<?= $this->url('blog-post6')?>">The importance of being away</a></h2></li>
        <li><h2><a href="<?= $this->url('blog-post1')?>">Interface injection with initializers in Zend\ServiceManager</a></h2></li>

        <li><h2><a href="<?= $this->url('blog-post2')?>">Using Zend Framework service managers in your application</a></h2></li>

        <li><h2><a href="<?= $this->url('blog-post3')?>">Use Soflomo\Prototype for quick website prototypes</a></h2></li>

        <li><h2><a href="<?= $this->url('blog-post4')?>">Strategies for hydrators: a practical use case</a></h2></li>

        <li><h2><a href="<?= $this->url('blog-post5')?>">Factories for translator loaders</a></h2></li>
    <ul>

    <a href="<?= $this->url('about-me')?>">About me</a>
</article>