<?php
    $this->headTitle()->set('About me')
?>

<section class="blog-article about-me" itemscope itemtype="http://schema.org/Person">
    <header>
        <h1 class="blog-article-title" itemprop="name">Jurian Sluiman</h1>
    </header>

    <img src="/assets/images/jurian.jpg" style="width:100%">

    <p>My name is Jurian Sluiman, a Dutch entrepreneur, founder of several companies and happy music lover. I am a graduated Msc student from Delft University of Technology and have expertise in software development, medical devices and medical processes.</p>

    <p><q>My goal is to create solutions that are usable and have a meaning for the people who use them</q></p>

    <p>Always in a search for innovation, I continuously explore the world behind the borders of my current knowledge. The pragmatic focus on products caused me to work with many people full of ideas. For me, the joy of life is to turn every good idea into a working product or service.</p>

    <h2>Experience</h2>
    <ul>
        <li><strong>Founder</strong> Doctors of Healthcare (2013 - present)</li>
        <li><strong>Founder</strong> Soflomo (2013 - present)</li>
        <li><strong>Intern</strong> Maquet GmbH &amp; CO. KG, Rastatt, Germany (2011)</li>
        <li><strong>Co-founder</strong> Librio (2010 - 2011)</li>
        <li><strong>Board member</strong> D.S.M.G. Krashna Musika (2007 - 2008)</li>
    </ul>

    <h2>Education</h2>
    <ul>
        <li><strong>Biomedical Engineering</strong> Delft University of Technology</li>
        <li><strong>Mechanical Engineering</strong> Delft University of Technology</li>
        <li><strong>Gymnasium</strong> Sint Maartenscollege Voorburg</li>
    </ul>

    <h2>Most read blog posts</h2>
    <ul>
        <li><a href="/article/120/using-zend-framework-service-managers-in-your-application">Using Zend Framework service managers in your application</a></li>
        <li><a href="/article/117/use-3rd-party-modules-in-zend-framework-2">Use 3rd party modules in Zend Framework 2</a></li>
        <li><a href="/article/125/strategies-for-hydrators-a-practical-use-case">Strategies for hydrators: a practical use case</a></li>
    </ul>

    <h2>Publications</h2>
    <ul>
        <li><em>Real-Time Patient Process Monitoring System &mdash; A design study of an information system at the Rotterdam Eye Hospital</em>, February 2013</li>
        <li><em>Design of a Real-Time Patient Process Monitoring System</em>, February 2013</li>
        <li><em>The usage of operational research and surgical workflow analysis to mitigate delays in the operative process</em>, May 2012</li>
    </ul>

    <h2>Profiles</h2>
    <ul>
        <li><a href="https://twitter.com/juriansluiman">@juriansluiman</a> on Twitter</li>
        <li><a href="https://plus.google.com/102726331143136952916?rel=author" rel="me">+Jurian Sluiman</a> on Google+</li>
        <li><a href="http://linkedin.com/in/juriansluiman">Jurian Sluiman</a> on LinkedIn</li>
        <li><a href="https://github.com/juriansluiman">juriansluiman</a> on Github</li>
    </ul>
</section>