<?php
    $this->headTitle()->set('The importance of being away')
?>

<article class="blog-article" itemprop="blogPosts" itemscope itemtype="http://schema.org/BlogPosting" contenteditable>
    <header>
        <time datetime="2011-11-06T13:42:04+01:00" pubdate itemprop="datePublished" content="2011-11-06" class="blog-article-publishdate">august 2013</time>
        <h1 itemprop="name" class="blog-article-title"><a href="" itemprop="url">The importance of being away</a></h1>
    </header>

    <p>Now the summer period is ending soon, I have had quite some conversions with my fellows about vacations.</p>
</article>