<?php
/**
 * @var $blog    Current blog
 * @var $article Article from this blog
 * @var $form    Form to edit article
 */

use IntlDateFormatter as Format;
$this->plugin('translate')->setTranslatorTextDomain('blog');

$this->headLink()->appendStylesheet($this->basePath() . '/components/redactor/redactor.css')
                 ->appendStylesheet($this->basePath() . '/components/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css')
                 ->appendStylesheet($this->basePath() . '/components/dropzone/downloads/css/basic.css');

$this->headScript()->appendFile($this->basePath() . '/components/requirejs/require.js');

$this->inlineScript()->appendFile($this->basePath() .'/components/redactor/redactor.min.js')
                     ->appendFile($this->basePath() .'/components/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js')
                     ->appendScript("
                        $(document).ready(
                            function()
                            {
                                $('.redactor').redactor({
                                    imageUpload: '/admin/image/upload',
                                    imageUploadErrorCallback: function(obj, json) {
                                        alert('Something went wrong with your image upload');
                                    },
                                    uploadFields: {
                                        'form': 'blog-image'
                                    },
                                    fileUpload: '/admin/file/upload',
                                    fileUploadErrorCallback: function(obj, json) {
                                        alert('Something went wrong with your file upload');
                                    },
                                    tabFocus: false,
                                    toolbarFixedBox: true,
                                    buttons: ['formatting', '|', 'bold', 'italic', '|', 'unorderedlist', 'orderedlist', 'outdent', 'indent', '|','image', 'video', 'file', 'link', '|', 'html']
                                });
                            }
                        );
                     ")
                     ->appendScript("requirejs.config({baseUrl: '/scripts'});
                        require(['admin/image'], function(image) {
                            image.init('.image-uploader');
                     });")
                     ->appendScript("
                        $(function() {
                            $('.blog-date').datetimepicker({
                                language: 'en'
                            });
                        });
                    ");
?>

<?
$image      = (isset($article) &&  $article->getImage() ? $article->getImage(): false);
$urlCreate  = $this->url('image');
$urlUpdate  = $this->url('image', array('image' => '%s'));
$urlDelete  = $this->url('image', array('image' => '%s'));

$formUpload = $this->imageUploadForm('blog-image', $urlCreate);
$formName   = $formUpload->getFileInputName();
?>


<?  $form->prepare()?>
<?= $this->form()->openTag($form)?>
    <button type="submit" class="btn blog-save-button top pull-right"><?= $this->translate("Save article")?></button>
    <?= $this->formRow($form->get('title')->setAttribute('class', 'span8')->setLabel( $this->translate("Title") ))?>
    <?= $this->formRow($form->get('lead')->setAttribute('class', 'redactor')->setLabel( $this->translate("Lead") ))?>

    <label><?= $this->translate("Image")?></label>
    <div class="image-uploader dropzone" data-url="<?= $urlCreate ?>" data-create="<?= $urlCreate ?>" data-update="<?= $urlUpdate ?>" data-delete="<?= $urlDelete ?>" data-image-field="blog-image" data-image-variant="blog-image">

    <?/*= $this->form()->openTag($formUpload->setAttributes(array(
            'class'               => 'image-uploader dropzone',
            'data-url'            => $urlCreate,
            'data-create'         => $urlCreate,
            'data-update'         => $urlUpdate,
            'data-delete'         => $urlDelete,
            'data-image-field'    => 'blog-image',
            'data-image-variant'  => 'blog-image',
            'data-image-template' => '<img src=\"%s\" data-image-id=\"%s\">',
        )))*/?>


        <div class="image-container">

            <div class="dz-message clickable" data-dz-message <? if($image) echo 'style="display: none;"'?>>
                <div class="dz-message-text">
                    <p><i class="icon-picture"></i></p>
                    <p><?= $this->translate("Drag image to upload (or click)")?></p>
                </div>
            </div>

            <? if ($image): ?>
                <img class="image-element clickable" src="<?= $image->getSource() ?>" data-image-id="<?= $image->getId() ?>">
                <div class="image-delete-container" data-dz-message>
                    <a href="<?//= $urlDelete?>" class="delete-image" data-confirm-message="Are you sure you want to remove this image?"><?= $this->translate("Remove image")?></a>
                </div>
            <? else: ?>
                <img class="image-element clickable" src="">
            <? endif ?>
        </div>

        <a class="image-upload-link clickable btn" style="display: none;"><?= $this->translate("Upload image")?></a>

        <?//= $this->formRow($formUpload->get($formName))?>
        <?//= $this->formElement($formUpload->get('form'))?>
    <?//= $this->form()->closeTag()?>

    </div>

    <?= $this->formRow($form->get('body')->setAttribute('class', 'redactor')->setLabel( $this->translate("Body") ))?>
    <?= $this->formRow($form->get('image')->setAttribute('id', 'blog-image'))?>
    <div class="input-append date blog-date">
        <?= $this->formLabel($form->get('publish_date')->setLabel( $this->translate("Publish date") ))?>
        <?= $this->formElement($form->get('publish_date')->setAttribute('data-format', 'yyyy-MM-dd hh:mm'))?>
        <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
        </span>
    </div>
    <button type="submit" class="btn blog-save-button pull-right"><?= $this->translate("Save article")?></button>
<?= $this->form()->closeTag()?>