<?php
/**
 * Listing of recent articles
 *
 * @var $articles Array or recent articles
 */
?>

<?php foreach ($articles as $article):?>
    <article class="blog-article">
        <h2><a href="<?php echo $this->url('/view', array(
            'article' => $article->getId(),
            'slug'    => $this->slug($article->getTitle()),
        ))?>">
            <?php echo $this->escapeHtml($article->getTitle())?>
        </a></h2>
        <p><?php echo $article->getLead()?></p>
    </article>
<?php endforeach ?>