<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Ensemble - Management Interface')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php echo $this->headLink()->prependStylesheet('//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css')
                                    ->appendStylesheet($this->basePath() . '/styles/css/admin.css?' . $this->version()) ?>

        <?php echo $this->headScript()->appendFile($this->basePath() . '/components/modernizr/modernizr.js') ?>
    </head>
    <body>

        <div class="navbar navbar-inverse">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('zfcadmin') ?>" title="Ensemble - Management Interface">Ensemble</a>
                    <div class="nav-collapse">
                        <?php echo $this->navigation('admin_navigation')
                                        ->menu()
                                        ->setUlClass('nav')
                                        ->setMaxDepth(0)
                                        ->setRenderInvisible(false)?>
                        <ul class="nav pull-right">
                            <li><a target="_blank" href="/">Open website <span class="icon-share"></span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row-fluid">

                <div class="span3">
                    <div class="sidebar-nav well">
                        <p class="nav-header">Manage page contents</p>
                        <?php echo $this->adminPageTree(); ?>
                    </div>
                </div>

                <div class="span9">
                    <?php echo $this->content; ?>
                </div>
            </div>

            <footer>
                <hr>
                <p>&copy; 2009 - 2013 Soflomo. All rights reserved.</p>
            </footer>

        </div>
        <?php echo $this->inlineScript()
            ->prependFile('//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js')
            ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js')
            ->appendFile($this->basePath() .'/scripts/admin.js?'. $this->version())
        ?>
    </body>
</html>