<?php
/**
 * General layout for juriansluiman.nl
 */
if (!isset($locale)) {
    $locale = Locale::getDefault();
}
if (!isset($pagetype)) {
    $pagetype = 'WebPage';
}
?>
<?= $this->doctype(); ?>

<html lang="<?= Locale::getPrimaryLanguage($locale)?>">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle()->setSeparator(' &middot; ')->setAutoEscape(false) ?>

    <?= $this->headMeta()->appendName('copyright', 'Jurian Sluiman 2006-2013')
                         ->appendName('generator', 'Ensemble CMF - Soflomo.com')
                         ->appendName('viewport', 'width=device-width, initial-scale=1')
                         ?>

    <?= $this->headLink()->prependStylesheet('//fast.fonts.net/cssapi/36620992-14f0-4ddb-91fb-f0f85808413d.css')
                         ->appendStylesheet($this->basePath() . '/styles/css/styles.css?' . $this->version())
                         ?>

    <?= $this->headScript() ?>
</head>

<body itemscope itemtype="http://schema.org/<?= $pagetype?>">
    <main role="main" id="content"><?= $this->content ?></main>

    <footer role="contentinfo" class="page-footer">
        <p>&copy; Jurian Sluiman 2006-2013 &mdash; All content is licensed under the <a href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons BY-SA 3.0</a>.</p>

        <nav>
        <ul class="navigation-footer">
            <li><a href="/">blog</a></li>
            <li><a href="/about">about me</a></li>
            <li><a href="/contact">contact</a></li>
        </ul>

        <!-- <ul class="navigation-footer">
            <li><a href="/category/programming">programming</a></li>
            <li><a href="/category/entrepreneur">entrepreneurial</a></li>
            <li><a href="/category/writing">random words</a></li>
        </ul> -->

        <ul class="navigation-footer">
            <li><a href="https://twitter.com/juriansluiman">twitter</a></li>
            <li><a href="https://linkedin.com/in/juriansluiman">linkedin</a></li>
            <li><a href="https://github.com/juriansluiman">github</a></li>
        </ul>
        </nav>
    </footer>

    <?= $this->inlineScript()->appendScript("WebFontConfig = {
  google: { families: [ 'Source Code Pro' ] }
};

(function() {
  var wf = document.createElement('script');
  wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
           '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
  wf.type = 'text/javascript';
  wf.async = 'true';

  var s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(wf, s);
})();") ?>
</body>
</html>
