<?php
    $this->headTitle('An error occurred');
?>
<h1>An error occurred</h1>
<p>
    <?php echo $this->message ?>
    <?php if(isset($this->exception)):?>
    <code><?= get_class($this->exception)?></code>: <?= $this->exception->getMessage()?>
    <?php endif?>
</p>

<p>
    <a href="http://www.flickr.com/photos/hikingartist/5727425824/"><img src="http://farm4.staticflickr.com/3259/5727425824_0d42007863_b.jpg" class="full-width"></a><br>
    <em>Image courtesy of Frits Ahlefeldt, <a href="http://hikingartist.com">hikingartist.com</a></em>
</p>

<p>Please <a href="/contact">let me know</a> what happened, so I can fix this problem.</p>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

<?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
<hr/>
<h2>Additional information:</h2>
<h3><?php echo get_class($this->exception); ?></h3>
<dl>
    <dt>File:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
    </dd>
    <dt>Message:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
    </dd>
    <dt>Stack trace:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
    </dd>
</dl>
<?php
    $e = $this->exception->getPrevious();
    if ($e) :
?>
<hr/>
<h2>Previous exceptions:</h2>
<ul class="unstyled">
    <?php while($e) : ?>
    <li>
        <h3><?php echo get_class($e); ?></h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
            </dd>
        </dl>
        <?php
                $e = $e->getPrevious();
            endwhile;
        ?>
    </li>
</ul>
<?php endif; ?>

<?php else: ?>

<h3>No Exception available</h3>

<?php endif ?>

<?php endif ?>